This exercise has been done with the help of videos on Knowledge Shelf YouTube Channel.

In [1]:
import pandas as pd

In [2]:
bond = pd.read_csv("JB007.csv", index_col="Film")

In [3]:
bond.sort_index(inplace=True)

For .query() method to work, it is mandatory that column names be string with no blank space.

In [4]:
bond.columns = [column_name.replace(" ","_") for column_name in bond.columns]

In [5]:
bond.head()

,Year,Years_lapse,Bond_actor,Bond_actor_appearance,Villians_Dispatched,Others'_Dispatched,Total_Dispatched,Adjusted_box_office,Actual_box_office,Adjusted_budget,...,Golden_Globe_wins,Academy_Award_nominations,Academy_Award_wins,Number_of_Bond_drinks,Bond_girls,Bond_car_make,Runtime_minutes,Month_released,Rating,"Bond,_James_Bond_said"
Film,,,,,,,,,,,,,,,,,,,,,
A View to a Kill,1985,2.0,Roger Moore,7,5,57,62,275.2,152.4,54.5,...,0,0,0,14.5,4,Renault,131,May,PG,2
Casino Royale,2006,4.0,Daniel Craig,1,11,11,22,581.5,594.2,145.3,...,0,0,0,26.0,2,Aston Martin,144,November,PG-13,1
Diamonds Are Forever,1971,2.0,Sean Connery,6,7,42,49,442.5,116.0,34.7,...,0,1,0,6.0,5,Ford,120,December,PG,1
Die Another Day,2002,3.0,Pierce Brosnan,4,31,20,51,465.4,431.9,154.2,...,0,0,0,5.5,3,Aston Martin,133,November,PG-13,1
Dr. No,1962,NaN,Sean Connery,1,4,8,12,448.8,59.5,7.0,...,1,0,0,11.5,3,Sunbeam,110,October,PG,1

In [6]:
bond.query('Bond_actor == "Sean Connery"')

,Year,Years_lapse,Bond_actor,Bond_actor_appearance,Villians_Dispatched,Others'_Dispatched,Total_Dispatched,Adjusted_box_office,Actual_box_office,Adjusted_budget,...,Golden_Globe_wins,Academy_Award_nominations,Academy_Award_wins,Number_of_Bond_drinks,Bond_girls,Bond_car_make,Runtime_minutes,Month_released,Rating,"Bond,_James_Bond_said"
Film,,,,,,,,,,,,,,,,,,,,,
Diamonds Are Forever,1971,2.0,Sean Connery,6,7,42,49,442.5,116.0,34.7,...,0,1,0,6.0,5,Ford,120,December,PG,1
Dr. No,1962,NaN,Sean Connery,1,4,8,12,448.8,59.5,7.0,...,1,0,0,11.5,3,Sunbeam,110,October,PG,1
From Russia With Love,1963,1.0,Sean Connery,2,11,16,27,543.8,78.9,12.6,...,0,0,0,16.0,3,Bentley,115,April,PG,0
Goldfinger,1964,1.0,Sean Connery,3,9,68,77,820.4,124.9,18.6,...,0,1,1,12.0,5,Aston Martin,110,September,PG,1
Thunderball,1965,1.0,Sean Connery,4,20,90,110,848.1,141.2,41.9,...,0,1,1,14.5,5,Lincoln,130,December,PG,0
You Only Live Twice,1967,2.0,Sean Connery,5,21,175,196,514.2,101.0,59.9,...,0,0,0,9.5,4,Toyota,117,June,PG,0

In [7]:
bond.query("Director == 'Terence Young'")

,Year,Years_lapse,Bond_actor,Bond_actor_appearance,Villians_Dispatched,Others'_Dispatched,Total_Dispatched,Adjusted_box_office,Actual_box_office,Adjusted_budget,...,Golden_Globe_wins,Academy_Award_nominations,Academy_Award_wins,Number_of_Bond_drinks,Bond_girls,Bond_car_make,Runtime_minutes,Month_released,Rating,"Bond,_James_Bond_said"
Film,,,,,,,,,,,,,,,,,,,,,
Dr. No,1962,NaN,Sean Connery,1,4,8,12,448.8,59.5,7.0,...,1,0,0,11.5,3,Sunbeam,110,October,PG,1
From Russia With Love,1963,1.0,Sean Connery,2,11,16,27,543.8,78.9,12.6,...,0,0,0,16.0,3,Bentley,115,April,PG,0
Thunderball,1965,1.0,Sean Connery,4,20,90,110,848.1,141.2,41.9,...,0,1,1,14.5,5,Lincoln,130,December,PG,0

In [8]:
bond.query("Bond_actor != 'Roger Moore'")

,Year,Years_lapse,Bond_actor,Bond_actor_appearance,Villians_Dispatched,Others'_Dispatched,Total_Dispatched,Adjusted_box_office,Actual_box_office,Adjusted_budget,...,Golden_Globe_wins,Academy_Award_nominations,Academy_Award_wins,Number_of_Bond_drinks,Bond_girls,Bond_car_make,Runtime_minutes,Month_released,Rating,"Bond,_James_Bond_said"
Film,,,,,,,,,,,,,,,,,,,,,
Casino Royale,2006,4.0,Daniel Craig,1,11,11,22,581.5,594.2,145.3,...,0,0,0,26.0,2,Aston Martin,144,November,PG-13,1
Diamonds Are Forever,1971,2.0,Sean Connery,6,7,42,49,442.5,116.0,34.7,...,0,1,0,6.0,5,Ford,120,December,PG,1
Die Another Day,2002,3.0,Pierce Brosnan,4,31,20,51,465.4,431.9,154.2,...,0,0,0,5.5,3,Aston Martin,133,November,PG-13,1
Dr. No,1962,NaN,Sean Connery,1,4,8,12,448.8,59.5,7.0,...,1,0,0,11.5,3,Sunbeam,110,October,PG,1
From Russia With Love,1963,1.0,Sean Connery,2,11,16,27,543.8,78.9,12.6,...,0,0,0,16.0,3,Bentley,115,April,PG,0
GoldenEye,1995,6.0,Pierce Brosnan,1,47,25,72,518.5,351.9,76.9,...,0,0,0,8.0,3,BMW,130,November,PG-13,1
Goldfinger,1964,1.0,Sean Connery,3,9,68,77,820.4,124.9,18.6,...,0,1,1,12.0,5,Aston Martin,110,September,PG,1
Licence to Kill,1989,2.0,Timothy Dalton,2,10,13,23,250.9,156.2,56.7,...,0,0,0,4.0,2,Lincoln,133,July,R,1
On Her Majesty's Secret Service,1969,2.0,George Lazenby,1,5,37,42,291.5,64.6,37.3,...,0,0,0,9.5,3,Aston Martin,142,December,PG,2
Quantum of Solace,2008,2.0,Daniel Craig,2,16,15,31,514.2,576.0,181.4,...,0,0,0,18.0,2,Aston Martin,106,November,PG-13,0
Skyfall,2012,4.0,Daniel Craig,3,26,23,49,879.8,1108.6,158.1,...,1,5,2,16.0,2,Aston Martin,143,November,PG-13,1
The Living Daylights,1987,2.0,Timothy Dalton,1,13,29,42,313.5,191.2,68.8,...,0,0,0,5.5,2,Aston Martin,130,June,PG,1
The World is Not Enough,1999,2.0,Pierce Brosnan,3,27,43,70,439.5,361.8,158.3,...,0,0,0,12.5,3,BMW,128,November,PG-13,2
Thunderball,1965,1.0,Sean Connery,4,20,90,110,848.1,141.2,41.9,...,0,1,1,14.5,5,Lincoln,130,December,PG,0
Tomorrow Never Dies,1997,2.0,Pierce Brosnan,2,30,24,54,463.2,338.9,133.9,...,0,0,0,22.0,3,BMW,119,December,PG-13,1
You Only Live Twice,1967,2.0,Sean Connery,5,21,175,196,514.2,101.0,59.9,...,0,0,0,9.5,4,Toyota,117,June,PG,0

In [9]:
bond.query('Bond_actor=="Roger Moore" and Director=="John Glen"')

,Year,Years_lapse,Bond_actor,Bond_actor_appearance,Villians_Dispatched,Others'_Dispatched,Total_Dispatched,Adjusted_box_office,Actual_box_office,Adjusted_budget,...,Golden_Globe_wins,Academy_Award_nominations,Academy_Award_wins,Number_of_Bond_drinks,Bond_girls,Bond_car_make,Runtime_minutes,Month_released,Rating,"Bond,_James_Bond_said"
Film,,,,,,,,,,,,,,,,,,,,,
A View to a Kill,1985,2.0,Roger Moore,7,5,57,62,275.2,152.4,54.5,...,0,0,0,14.5,4,Renault,131,May,PG,2
For Your Eyes Only,1981,2.0,Roger Moore,5,18,36,54,449.4,194.9,60.2,...,0,1,0,10.5,3,Lotus,127,June,PG,2
Octopussy,1983,2.0,Roger Moore,6,15,43,58,373.8,183.7,53.9,...,0,0,0,14.5,3,Mercedes-Benz,131,June,PG,1

In [10]:
bond.query('Bond_actor=="Roger Moore" or Director=="John Glen"')

,Year,Years_lapse,Bond_actor,Bond_actor_appearance,Villians_Dispatched,Others'_Dispatched,Total_Dispatched,Adjusted_box_office,Actual_box_office,Adjusted_budget,...,Golden_Globe_wins,Academy_Award_nominations,Academy_Award_wins,Number_of_Bond_drinks,Bond_girls,Bond_car_make,Runtime_minutes,Month_released,Rating,"Bond,_James_Bond_said"
Film,,,,,,,,,,,,,,,,,,,,,
A View to a Kill,1985,2.0,Roger Moore,7,5,57,62,275.2,152.4,54.5,...,0,0,0,14.5,4,Renault,131,May,PG,2
For Your Eyes Only,1981,2.0,Roger Moore,5,18,36,54,449.4,194.9,60.2,...,0,1,0,10.5,3,Lotus,127,June,PG,2
Licence to Kill,1989,2.0,Timothy Dalton,2,10,13,23,250.9,156.2,56.7,...,0,0,0,4.0,2,Lincoln,133,July,R,1
Live and Let Die,1973,2.0,Roger Moore,1,8,5,13,460.3,126.4,30.8,...,0,1,0,15.5,3,Chevrolet,121,June,PG,1
Moonraker,1979,2.0,Roger Moore,4,12,69,81,535.0,210.3,91.5,...,0,1,0,7.0,4,Bentley,126,June,PG,1
Octopussy,1983,2.0,Roger Moore,6,15,43,58,373.8,183.7,53.9,...,0,0,0,14.5,3,Mercedes-Benz,131,June,PG,1
The Living Daylights,1987,2.0,Timothy Dalton,1,13,29,42,313.5,191.2,68.8,...,0,0,0,5.5,2,Aston Martin,130,June,PG,1
The Man with the Golden Gun,1974,1.0,Roger Moore,2,1,5,6,334.0,98.5,27.7,...,0,0,0,11.5,4,AMC,125,December,PG,2
The Spy Who Loved Me,1977,3.0,Roger Moore,3,31,116,147,533.0,185.4,45.1,...,0,3,0,7.0,3,Lotus,125,July,PG,1

In [11]:
bond.query('Bond_actor in ["Timothy Dalton","George Lazenby"]')

,Year,Years_lapse,Bond_actor,Bond_actor_appearance,Villians_Dispatched,Others'_Dispatched,Total_Dispatched,Adjusted_box_office,Actual_box_office,Adjusted_budget,...,Golden_Globe_wins,Academy_Award_nominations,Academy_Award_wins,Number_of_Bond_drinks,Bond_girls,Bond_car_make,Runtime_minutes,Month_released,Rating,"Bond,_James_Bond_said"
Film,,,,,,,,,,,,,,,,,,,,,
Licence to Kill,1989,2.0,Timothy Dalton,2,10,13,23,250.9,156.2,56.7,...,0,0,0,4.0,2,Lincoln,133,July,R,1
On Her Majesty's Secret Service,1969,2.0,George Lazenby,1,5,37,42,291.5,64.6,37.3,...,0,0,0,9.5,3,Aston Martin,142,December,PG,2
The Living Daylights,1987,2.0,Timothy Dalton,1,13,29,42,313.5,191.2,68.8,...,0,0,0,5.5,2,Aston Martin,130,June,PG,1

In [12]:
bond.query("Bond_actor not in ['Sean Connery','Roger Moore']")

,Year,Years_lapse,Bond_actor,Bond_actor_appearance,Villians_Dispatched,Others'_Dispatched,Total_Dispatched,Adjusted_box_office,Actual_box_office,Adjusted_budget,...,Golden_Globe_wins,Academy_Award_nominations,Academy_Award_wins,Number_of_Bond_drinks,Bond_girls,Bond_car_make,Runtime_minutes,Month_released,Rating,"Bond,_James_Bond_said"
Film,,,,,,,,,,,,,,,,,,,,,
Casino Royale,2006,4.0,Daniel Craig,1,11,11,22,581.5,594.2,145.3,...,0,0,0,26.0,2,Aston Martin,144,November,PG-13,1
Die Another Day,2002,3.0,Pierce Brosnan,4,31,20,51,465.4,431.9,154.2,...,0,0,0,5.5,3,Aston Martin,133,November,PG-13,1
GoldenEye,1995,6.0,Pierce Brosnan,1,47,25,72,518.5,351.9,76.9,...,0,0,0,8.0,3,BMW,130,November,PG-13,1
Licence to Kill,1989,2.0,Timothy Dalton,2,10,13,23,250.9,156.2,56.7,...,0,0,0,4.0,2,Lincoln,133,July,R,1
On Her Majesty's Secret Service,1969,2.0,George Lazenby,1,5,37,42,291.5,64.6,37.3,...,0,0,0,9.5,3,Aston Martin,142,December,PG,2
Quantum of Solace,2008,2.0,Daniel Craig,2,16,15,31,514.2,576.0,181.4,...,0,0,0,18.0,2,Aston Martin,106,November,PG-13,0
Skyfall,2012,4.0,Daniel Craig,3,26,23,49,879.8,1108.6,158.1,...,1,5,2,16.0,2,Aston Martin,143,November,PG-13,1
The Living Daylights,1987,2.0,Timothy Dalton,1,13,29,42,313.5,191.2,68.8,...,0,0,0,5.5,2,Aston Martin,130,June,PG,1
The World is Not Enough,1999,2.0,Pierce Brosnan,3,27,43,70,439.5,361.8,158.3,...,0,0,0,12.5,3,BMW,128,November,PG-13,2
Tomorrow Never Dies,1997,2.0,Pierce Brosnan,2,30,24,54,463.2,338.9,133.9,...,0,0,0,22.0,3,BMW,119,December,PG-13,1