This exercise has been done with the help of videos on Knowledge Shelf YouTube Channel.

In [1]:
import pandas as pd

In [2]:
bond = pd.read_csv("JB007.csv", index_col="Film")

In [3]:
bond.head()

,Year,Years lapse,Bond actor,Bond actor appearance,Villians Dispatched,Others' Dispatched,Total Dispatched,Adjusted box office,Actual box office,Adjusted budget,...,Golden Globe wins,Academy Award nominations,Academy Award wins,Number of Bond drinks,Bond girls,Bond car make,Runtime minutes,Month released,Rating,"Bond, James Bond said"
Film,,,,,,,,,,,,,,,,,,,,,
Dr. No,1962,NaN,Sean Connery,1,4,8,12,448.8,59.5,7.0,...,1,0,0,11.5,3,Sunbeam,110,October,PG,1
From Russia With Love,1963,1.0,Sean Connery,2,11,16,27,543.8,78.9,12.6,...,0,0,0,16.0,3,Bentley,115,April,PG,0
Goldfinger,1964,1.0,Sean Connery,3,9,68,77,820.4,124.9,18.6,...,0,1,1,12.0,5,Aston Martin,110,September,PG,1
Thunderball,1965,1.0,Sean Connery,4,20,90,110,848.1,141.2,41.9,...,0,1,1,14.5,5,Lincoln,130,December,PG,0
You Only Live Twice,1967,2.0,Sean Connery,5,21,175,196,514.2,101.0,59.9,...,0,0,0,9.5,4,Toyota,117,June,PG,0

loc stands for location.

In [4]:
bond.sort_index(inplace=True)
# It will alphabetically sort the table based on index column "Film".

In [5]:
bond.head()

,Year,Years lapse,Bond actor,Bond actor appearance,Villians Dispatched,Others' Dispatched,Total Dispatched,Adjusted box office,Actual box office,Adjusted budget,...,Golden Globe wins,Academy Award nominations,Academy Award wins,Number of Bond drinks,Bond girls,Bond car make,Runtime minutes,Month released,Rating,"Bond, James Bond said"
Film,,,,,,,,,,,,,,,,,,,,,
A View to a Kill,1985,2.0,Roger Moore,7,5,57,62,275.2,152.4,54.5,...,0,0,0,14.5,4,Renault,131,May,PG,2
Casino Royale,2006,4.0,Daniel Craig,1,11,11,22,581.5,594.2,145.3,...,0,0,0,26.0,2,Aston Martin,144,November,PG-13,1
Diamonds Are Forever,1971,2.0,Sean Connery,6,7,42,49,442.5,116.0,34.7,...,0,1,0,6.0,5,Ford,120,December,PG,1
Die Another Day,2002,3.0,Pierce Brosnan,4,31,20,51,465.4,431.9,154.2,...,0,0,0,5.5,3,Aston Martin,133,November,PG-13,1
Dr. No,1962,NaN,Sean Connery,1,4,8,12,448.8,59.5,7.0,...,1,0,0,11.5,3,Sunbeam,110,October,PG,1

In [6]:
bond.loc["Die Another Day"]

Year                                        2002
Years lapse                                    3
Bond actor                        Pierce Brosnan
Bond actor appearance                          4
Villians Dispatched                           31
Others' Dispatched                            20
Total Dispatched                              51
Adjusted box office                        465.4
Actual box office                          431.9
Adjusted budget                            154.2
Actual budget                                142
Director                            Lee Tamahori
Rotten Tomatoes critic score                 57%
Rotten Tomatoes audience score               41%
Golden Globe nominations                       1
Golden Globe wins                              0
Academy Award nominations                      0
Academy Award wins                             0
Number of Bond drinks                        5.5
Bond girls                                     3
Bond car make                       Aston Martin
Runtime minutes                              133
Month released                          November
Rating                                     PG-13
Bond, James Bond said                          1
Name: Die Another Day, dtype: object

In [7]:
bond.loc["Casino Royale"]

Year                                         2006
Years lapse                                     4
Bond actor                           Daniel Craig
Bond actor appearance                           1
Villians Dispatched                            11
Others' Dispatched                             11
Total Dispatched                               22
Adjusted box office                         581.5
Actual box office                           594.2
Adjusted budget                             145.3
Actual budget                                 150
Director                          Martin Campbell
Rotten Tomatoes critic score                  95%
Rotten Tomatoes audience score                89%
Golden Globe nominations                        0
Golden Globe wins                               0
Academy Award nominations                       0
Academy Award wins                              0
Number of Bond drinks                          26
Bond girls                                      2
Bond car make                        Aston Martin
Runtime minutes                               144
Month released                           November
Rating                                      PG-13
Bond, James Bond said                           1
Name: Casino Royale, dtype: object

In [8]:
bond.loc["Diamonds Are Forever":"Moonraker"]

,Year,Years lapse,Bond actor,Bond actor appearance,Villians Dispatched,Others' Dispatched,Total Dispatched,Adjusted box office,Actual box office,Adjusted budget,...,Golden Globe wins,Academy Award nominations,Academy Award wins,Number of Bond drinks,Bond girls,Bond car make,Runtime minutes,Month released,Rating,"Bond, James Bond said"
Film,,,,,,,,,,,,,,,,,,,,,
Diamonds Are Forever,1971,2.0,Sean Connery,6,7,42,49,442.5,116.0,34.7,...,0,1,0,6.0,5,Ford,120,December,PG,1
Die Another Day,2002,3.0,Pierce Brosnan,4,31,20,51,465.4,431.9,154.2,...,0,0,0,5.5,3,Aston Martin,133,November,PG-13,1
Dr. No,1962,NaN,Sean Connery,1,4,8,12,448.8,59.5,7.0,...,1,0,0,11.5,3,Sunbeam,110,October,PG,1
For Your Eyes Only,1981,2.0,Roger Moore,5,18,36,54,449.4,194.9,60.2,...,0,1,0,10.5,3,Lotus,127,June,PG,2
From Russia With Love,1963,1.0,Sean Connery,2,11,16,27,543.8,78.9,12.6,...,0,0,0,16.0,3,Bentley,115,April,PG,0
GoldenEye,1995,6.0,Pierce Brosnan,1,47,25,72,518.5,351.9,76.9,...,0,0,0,8.0,3,BMW,130,November,PG-13,1
Goldfinger,1964,1.0,Sean Connery,3,9,68,77,820.4,124.9,18.6,...,0,1,1,12.0,5,Aston Martin,110,September,PG,1
Licence to Kill,1989,2.0,Timothy Dalton,2,10,13,23,250.9,156.2,56.7,...,0,0,0,4.0,2,Lincoln,133,July,R,1
Live and Let Die,1973,2.0,Roger Moore,1,8,5,13,460.3,126.4,30.8,...,0,1,0,15.5,3,Chevrolet,121,June,PG,1
Moonraker,1979,2.0,Roger Moore,4,12,69,81,535.0,210.3,91.5,...,0,1,0,7.0,4,Bentley,126,June,PG,1

In [9]:
bond.loc["Dr. No":] # from "Dr. No" till last row of the table will be diaplayed.

,Year,Years lapse,Bond actor,Bond actor appearance,Villians Dispatched,Others' Dispatched,Total Dispatched,Adjusted box office,Actual box office,Adjusted budget,...,Golden Globe wins,Academy Award nominations,Academy Award wins,Number of Bond drinks,Bond girls,Bond car make,Runtime minutes,Month released,Rating,"Bond, James Bond said"
Film,,,,,,,,,,,,,,,,,,,,,
Dr. No,1962,NaN,Sean Connery,1,4,8,12,448.8,59.5,7.0,...,1,0,0,11.5,3,Sunbeam,110,October,PG,1
For Your Eyes Only,1981,2.0,Roger Moore,5,18,36,54,449.4,194.9,60.2,...,0,1,0,10.5,3,Lotus,127,June,PG,2
From Russia With Love,1963,1.0,Sean Connery,2,11,16,27,543.8,78.9,12.6,...,0,0,0,16.0,3,Bentley,115,April,PG,0
GoldenEye,1995,6.0,Pierce Brosnan,1,47,25,72,518.5,351.9,76.9,...,0,0,0,8.0,3,BMW,130,November,PG-13,1
Goldfinger,1964,1.0,Sean Connery,3,9,68,77,820.4,124.9,18.6,...,0,1,1,12.0,5,Aston Martin,110,September,PG,1
Licence to Kill,1989,2.0,Timothy Dalton,2,10,13,23,250.9,156.2,56.7,...,0,0,0,4.0,2,Lincoln,133,July,R,1
Live and Let Die,1973,2.0,Roger Moore,1,8,5,13,460.3,126.4,30.8,...,0,1,0,15.5,3,Chevrolet,121,June,PG,1
Moonraker,1979,2.0,Roger Moore,4,12,69,81,535.0,210.3,91.5,...,0,1,0,7.0,4,Bentley,126,June,PG,1
Octopussy,1983,2.0,Roger Moore,6,15,43,58,373.8,183.7,53.9,...,0,0,0,14.5,3,Mercedes-Benz,131,June,PG,1
On Her Majesty's Secret Service,1969,2.0,George Lazenby,1,5,37,42,291.5,64.6,37.3,...,0,0,0,9.5,3,Aston Martin,142,December,PG,2
Quantum of Solace,2008,2.0,Daniel Craig,2,16,15,31,514.2,576.0,181.4,...,0,0,0,18.0,2,Aston Martin,106,November,PG-13,0
Skyfall,2012,4.0,Daniel Craig,3,26,23,49,879.8,1108.6,158.1,...,1,5,2,16.0,2,Aston Martin,143,November,PG-13,1
The Living Daylights,1987,2.0,Timothy Dalton,1,13,29,42,313.5,191.2,68.8,...,0,0,0,5.5,2,Aston Martin,130,June,PG,1
The Man with the Golden Gun,1974,1.0,Roger Moore,2,1,5,6,334.0,98.5,27.7,...,0,0,0,11.5,4,AMC,125,December,PG,2
The Spy Who Loved Me,1977,3.0,Roger Moore,3,31,116,147,533.0,185.4,45.1,...,0,3,0,7.0,3,Lotus,125,July,PG,1
The World is Not Enough,1999,2.0,Pierce Brosnan,3,27,43,70,439.5,361.8,158.3,...,0,0,0,12.5,3,BMW,128,November,PG-13,2
Thunderball,1965,1.0,Sean Connery,4,20,90,110,848.1,141.2,41.9,...,0,1,1,14.5,5,Lincoln,130,December,PG,0
Tomorrow Never Dies,1997,2.0,Pierce Brosnan,2,30,24,54,463.2,338.9,133.9,...,0,0,0,22.0,3,BMW,119,December,PG-13,1
You Only Live Twice,1967,2.0,Sean Connery,5,21,175,196,514.2,101.0,59.9,...,0,0,0,9.5,4,Toyota,117,June,PG,0

In [10]:
bond.loc[:"On Her Majesty's Secret Serices"] 
# It will diaplay from beginning of the table to "On Her Majesty's Secret Services"

,Year,Years lapse,Bond actor,Bond actor appearance,Villians Dispatched,Others' Dispatched,Total Dispatched,Adjusted box office,Actual box office,Adjusted budget,...,Golden Globe wins,Academy Award nominations,Academy Award wins,Number of Bond drinks,Bond girls,Bond car make,Runtime minutes,Month released,Rating,"Bond, James Bond said"
Film,,,,,,,,,,,,,,,,,,,,,
A View to a Kill,1985,2.0,Roger Moore,7,5,57,62,275.2,152.4,54.5,...,0,0,0,14.5,4,Renault,131,May,PG,2
Casino Royale,2006,4.0,Daniel Craig,1,11,11,22,581.5,594.2,145.3,...,0,0,0,26.0,2,Aston Martin,144,November,PG-13,1
Diamonds Are Forever,1971,2.0,Sean Connery,6,7,42,49,442.5,116.0,34.7,...,0,1,0,6.0,5,Ford,120,December,PG,1
Die Another Day,2002,3.0,Pierce Brosnan,4,31,20,51,465.4,431.9,154.2,...,0,0,0,5.5,3,Aston Martin,133,November,PG-13,1
Dr. No,1962,NaN,Sean Connery,1,4,8,12,448.8,59.5,7.0,...,1,0,0,11.5,3,Sunbeam,110,October,PG,1
For Your Eyes Only,1981,2.0,Roger Moore,5,18,36,54,449.4,194.9,60.2,...,0,1,0,10.5,3,Lotus,127,June,PG,2
From Russia With Love,1963,1.0,Sean Connery,2,11,16,27,543.8,78.9,12.6,...,0,0,0,16.0,3,Bentley,115,April,PG,0
GoldenEye,1995,6.0,Pierce Brosnan,1,47,25,72,518.5,351.9,76.9,...,0,0,0,8.0,3,BMW,130,November,PG-13,1
Goldfinger,1964,1.0,Sean Connery,3,9,68,77,820.4,124.9,18.6,...,0,1,1,12.0,5,Aston Martin,110,September,PG,1
Licence to Kill,1989,2.0,Timothy Dalton,2,10,13,23,250.9,156.2,56.7,...,0,0,0,4.0,2,Lincoln,133,July,R,1
Live and Let Die,1973,2.0,Roger Moore,1,8,5,13,460.3,126.4,30.8,...,0,1,0,15.5,3,Chevrolet,121,June,PG,1
Moonraker,1979,2.0,Roger Moore,4,12,69,81,535.0,210.3,91.5,...,0,1,0,7.0,4,Bentley,126,June,PG,1
Octopussy,1983,2.0,Roger Moore,6,15,43,58,373.8,183.7,53.9,...,0,0,0,14.5,3,Mercedes-Benz,131,June,PG,1

In [11]:
bond.loc[["Live and Let Die", "Licence to Kill"]]
# it will display these two rows only.

,Year,Years lapse,Bond actor,Bond actor appearance,Villians Dispatched,Others' Dispatched,Total Dispatched,Adjusted box office,Actual box office,Adjusted budget,...,Golden Globe wins,Academy Award nominations,Academy Award wins,Number of Bond drinks,Bond girls,Bond car make,Runtime minutes,Month released,Rating,"Bond, James Bond said"
Film,,,,,,,,,,,,,,,,,,,,,
Live and Let Die,1973,2.0,Roger Moore,1,8,5,13,460.3,126.4,30.8,...,0,1,0,15.5,3,Chevrolet,121,June,PG,1
Licence to Kill,1989,2.0,Timothy Dalton,2,10,13,23,250.9,156.2,56.7,...,0,0,0,4.0,2,Lincoln,133,July,R,1

In [12]:
bond.loc[["Gold Bond", "Octopussy", "Moonraker"]]
# "Gold Bond" being no such movie, all data in that row will be NaN.

C:\Users\CA DHEERAJ\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning:
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#deprecate-loc-reindex-listlike
  """Entry point for launching an IPython kernel.

,Year,Years lapse,Bond actor,Bond actor appearance,Villians Dispatched,Others' Dispatched,Total Dispatched,Adjusted box office,Actual box office,Adjusted budget,...,Golden Globe wins,Academy Award nominations,Academy Award wins,Number of Bond drinks,Bond girls,Bond car make,Runtime minutes,Month released,Rating,"Bond, James Bond said"
Film,,,,,,,,,,,,,,,,,,,,,
Gold Bond,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Octopussy,1983.0,2.0,Roger Moore,6.0,15.0,43.0,58.0,373.8,183.7,53.9,...,0.0,0.0,0.0,14.5,3.0,Mercedes-Benz,131.0,June,PG,1.0
Moonraker,1979.0,2.0,Roger Moore,4.0,12.0,69.0,81.0,535.0,210.3,91.5,...,0.0,1.0,0.0,7.0,4.0,Bentley,126.0,June,PG,1.0

In [13]:
"Gold Bond" in bond.index

False

Here output False means "Gold Bond" doesn't exist in dataset.