This exercise has been done with the help of videos on Knowledge Shelf YouTube Channel.

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("employee.csv", parse_dates=["DateofHire","DateofTermination"])
df["HispanicLatino"] = df['HispanicLatino'].astype('bool')
df['GenderID'] = df['GenderID'].astype('category')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 310 entries, 0 to 309
Data columns (total 35 columns):
Employee_Name                 310 non-null object
EmpID                         310 non-null int64
MarriedID                     310 non-null int64
MaritalStatusID               310 non-null int64
GenderID                      310 non-null category
EmpStatusID                   310 non-null int64
DeptID                        310 non-null int64
PerfScoreID                   310 non-null int64
FromDiversityJobFairID        310 non-null int64
PayRate                       310 non-null float64
Termd                         310 non-null int64
PositionID                    310 non-null int64
Position                      310 non-null object
State                         310 non-null object
Zip                           310 non-null int64
DOB                           310 non-null object
Sex                           310 non-null object
MaritalDesc                   310 non-null object
CitizenDesc                   310 non-null object
HispanicLatino                310 non-null bool
RaceDesc                      310 non-null object
DateofHire                    310 non-null datetime64[ns]
DateofTermination             103 non-null datetime64[ns]
TermReason                    309 non-null object
EmploymentStatus              310 non-null object
Department                    310 non-null object
ManagerName                   310 non-null object
ManagerID                     302 non-null float64
RecruitmentSource             310 non-null object
PerformanceScore              310 non-null object
EngagementSurvey              310 non-null float64
EmpSatisfaction               310 non-null int64
SpecialProjectsCount          310 non-null int64
LastPerformanceReview_Date    207 non-null object
DaysLateLast30                207 non-null float64
dtypes: bool(1), category(1), datetime64[ns](2), float64(4), int64(12), object(15)
memory usage: 80.7+ KB

In [4]:
df['GenderID'] == 0
# here all the entries in 'GenderID' column will be compared to see if it is 0 (Zero). In case of a match, it will
# return "True", else "False".

0       True
1      False
2      False
3       True
4       True
       ...
305     True
306    False
307    False
308    False
309     True
Name: GenderID, Length: 310, dtype: bool

In [5]:
df[df["GenderID"] == 1] # It will output only those rows where "GenderID" is 1.

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,PayRate,...,Department,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30
1,"LaRotonda, William",1106026572,0,2,1,1,1,3,0,23.0,...,Admin Offices,Brandon R. LeBlanc,1.0,Website Banner Ads,Fully Meets,5.00,4,4,1/17/2019,0.0
2,"Steans, Tyrone",1302053333,0,0,1,1,1,3,0,29.0,...,Admin Offices,Brandon R. LeBlanc,1.0,Internet Search,Fully Meets,3.90,5,5,1/18/2019,0.0
9,"Digitale, Alfred",1306059197,1,1,1,1,6,3,0,56.0,...,Sales,John Smith,17.0,Pay Per Click - Google,Fully Meets,3.60,5,0,1/30/2019,0.0
10,"Friedman, Gerry",1204032843,0,0,1,1,6,3,1,55.5,...,Sales,John Smith,17.0,Diversity Job Fair,Fully Meets,3.65,5,0,1/17/2019,0.0
12,"Gonzales, Ricardo",1411071481,1,1,1,1,6,3,0,55.5,...,Sales,John Smith,17.0,Monster.com,Fully Meets,3.98,3,0,1/28/2019,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
301,"Ait Sidi, Karthikeyan",1307060199,1,1,1,5,3,3,0,62.0,...,IT/IS,Simon Roup,4.0,Company Intranet - Partner,Fully Meets,4.96,3,6,NaN,NaN
303,"Favis, Donald",1412071562,0,0,1,4,3,3,0,58.2,...,IT/IS,Simon Roup,4.0,Vendor Referral,Fully Meets,2.94,5,7,NaN,NaN
306,"Lajiri, Jyoti",1108028108,1,1,1,3,3,3,0,56.2,...,IT/IS,Peter Monroe,7.0,Employee Referral,Fully Meets,4.46,5,6,01-07-2019,0.0
307,"Semizoglou, Jeremiah",904013591,1,1,1,2,3,3,0,53.8,...,IT/IS,Peter Monroe,7.0,On-campus Recruiting,Fully Meets,3.27,4,5,1/14/2019,0.0
308,"South, Joe",1308060959,0,0,1,1,3,3,0,53.0,...,IT/IS,Peter Monroe,7.0,Employee Referral,Fully Meets,5.00,3,4,01-02-2019,0.0

In [6]:
df[df["Department"] == 'Sales'] # It will output only those rows where "Department" is "Sales".

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,PayRate,...,Department,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30
6,"Bunbury, Jessica",1504073368,1,1,0,5,6,3,0,55.00,...,Sales,John Smith,17.0,Social Networks - Facebook Twitter etc,Fully Meets,3.14,5,0,NaN,NaN
7,"Carter, Michelle",1403065721,0,0,0,1,6,3,0,55.00,...,Sales,John Smith,17.0,Billboard,Fully Meets,5.00,5,0,1/21/2019,0.0
8,"Dietrich, Jenna",1408069481,0,0,0,1,6,1,0,55.00,...,Sales,John Smith,17.0,Website Banner Ads,PIP,2.30,1,0,1/29/2019,0.0
9,"Digitale, Alfred",1306059197,1,1,1,1,6,3,0,56.00,...,Sales,John Smith,17.0,Pay Per Click - Google,Fully Meets,3.60,5,0,1/30/2019,0.0
10,"Friedman, Gerry",1204032843,0,0,1,1,6,3,1,55.50,...,Sales,John Smith,17.0,Diversity Job Fair,Fully Meets,3.65,5,0,1/17/2019,0.0
11,"Gill, Whitney",1302053046,0,4,0,4,6,3,0,55.00,...,Sales,John Smith,17.0,Monster.com,Fully Meets,3.97,4,0,NaN,NaN
12,"Gonzales, Ricardo",1411071481,1,1,1,1,6,3,0,55.50,...,Sales,John Smith,17.0,Monster.com,Fully Meets,3.98,3,0,1/28/2019,0.0
13,"Guilianno, Mike",1001167253,0,0,1,5,6,3,0,55.00,...,Sales,John Smith,17.0,Newspager/Magazine,Fully Meets,4.50,5,0,NaN,NaN
14,"Leruth, Giovanni",1412071660,0,3,1,1,6,3,0,55.00,...,Sales,John Smith,17.0,Website Banner Ads,Fully Meets,4.53,3,0,1/29/2019,0.0
15,"Mullaney, Howard",1306057978,0,0,1,1,6,1,0,55.00,...,Sales,John Smith,17.0,Internet Search,PIP,1.93,3,0,1/30/2019,0.0
16,"Ozark, Travis",812011761,0,0,1,1,6,3,0,55.00,...,Sales,John Smith,17.0,Website Banner Ads,Fully Meets,5.00,5,0,1/14/2019,0.0
17,"Strong, Caitrin",1411071295,1,1,0,1,6,3,0,54.00,...,Sales,John Smith,17.0,Professional Society,Fully Meets,2.00,4,0,1/31/2019,0.0
18,"Valentin,Jackie",1312063714,1,1,0,1,6,3,0,55.00,...,Sales,John Smith,17.0,Other,Fully Meets,2.81,3,0,1/17/2019,0.0
19,"Villanueva, Noah",1111030503,0,0,1,1,6,3,0,56.00,...,Sales,John Smith,17.0,Website Banner Ads,Fully Meets,1.77,4,0,1/18/2019,0.0
20,"Buck, Edward",1504073313,1,1,1,1,6,3,0,55.00,...,Sales,Lynn Daneault,21.0,Employee Referral,Fully Meets,3.31,5,0,1/28/2019,0.0
21,"Costa, Latia",1409070567,0,0,0,1,6,4,0,55.00,...,Sales,Lynn Daneault,21.0,Other,Exceeds,4.77,5,0,1/27/2019,0.0
22,"Fraval, Maruk",1411071302,0,0,1,1,6,3,0,55.00,...,Sales,Lynn Daneault,21.0,Monster.com,Fully Meets,1.64,3,0,1/27/2019,0.0
23,"Givens, Myriam",1203032099,0,0,0,1,6,3,0,55.00,...,Sales,Lynn Daneault,21.0,Pay Per Click - Google,Fully Meets,1.72,5,0,1/25/2019,0.0
24,Jeremy Prater,1001084890,1,1,1,1,6,1,0,56.00,...,Sales,Lynn Daneault,21.0,Website Banner Ads,PIP,1.81,2,0,1/17/2019,0.0
25,"Khemmich, Bartholemew",1104025008,0,0,1,1,6,3,0,55.00,...,Sales,Lynn Daneault,21.0,Pay Per Click - Google,Fully Meets,2.19,5,0,1/22/2019,0.0
26,"Martins, Joseph",1209048771,0,0,1,1,6,3,0,56.00,...,Sales,Lynn Daneault,21.0,Employee Referral,Fully Meets,2.94,5,0,1/19/2019,0.0
27,"McKinzie, Jac",1209049326,1,1,1,2,6,3,0,55.00,...,Sales,Lynn Daneault,21.0,Website Banner Ads,Fully Meets,2.91,4,0,1/29/2019,0.0
28,"Nguyen, Dheepa",1111030684,0,0,0,1,6,3,0,55.00,...,Sales,Lynn Daneault,21.0,Pay Per Click - Google,Fully Meets,5.00,5,0,1/25/2019,0.0
29,"Onque, Jasmine",1501072180,0,0,0,1,6,3,0,57.00,...,Sales,Lynn Daneault,21.0,Pay Per Click - Google,Fully Meets,4.28,3,0,1/25/2019,0.0
30,"Potts, Xana",1102024106,1,1,0,1,6,3,0,55.00,...,Sales,Lynn Daneault,21.0,Website Banner Ads,Fully Meets,4.20,5,0,02-01-2019,0.0
31,"Riordan, Michael",1502072711,0,3,1,1,6,4,0,55.00,...,Sales,Lynn Daneault,21.0,Billboard,Exceeds,4.10,3,0,01-04-2019,0.0
32,"Terry, Sharlene",1401064637,0,0,0,1,6,3,0,55.00,...,Sales,Lynn Daneault,21.0,Monster.com,Fully Meets,3.69,3,0,1/28/2019,0.0
54,"Houlihan, Debra",1009021646,1,1,0,1,6,3,0,60.00,...,Sales,Janet King,2.0,MBTA ads,Fully Meets,1.22,4,0,1/21/2019,0.0
281,"Daneault, Lynn",1402065303,0,0,0,1,6,3,0,54.00,...,Sales,Debra Houlihan,15.0,Pay Per Click - Google,Fully Meets,4.62,4,0,1/24/2019,0.0
282,"Kampew, Donysha",1109029264,0,0,0,5,6,3,0,60.25,...,Sales,Debra Houlihan,15.0,Social Networks - Facebook Twitter etc,Fully Meets,1.90,5,0,NaN,NaN
283,"Smith, John",1499902910,0,2,1,1,6,2,1,56.00,...,Sales,Debra Houlihan,15.0,Diversity Job Fair,Needs Improvement,1.62,4,0,1/16/2019,0.0

Same thing can be done in a different way mentioned below:

In [7]:
mask = df["Department"] == "IT/IS"

In [8]:
df[mask] # Now, we will get only those rows where "Department" is "Production".

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,PayRate,...,Department,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30
33,"Rachael, Maggie",1009919940,1,1,0,1,3,3,0,45.00,...,IT/IS,Brian Champaigne,13.0,Indeed,Fully Meets,2.02,4,6,02-06-2019,0.0
34,"Smith, Jason",1009919980,0,0,1,1,3,3,0,46.00,...,IT/IS,Brian Champaigne,13.0,Indeed,Fully Meets,3.01,5,7,1/23/2019,0.0
35,"Westinghouse, Matthew",1009919990,1,1,1,1,3,3,0,45.00,...,IT/IS,Brian Champaigne,13.0,Indeed,Fully Meets,1.82,3,6,01-02-2019,0.0
36,"Hubert, Robert",1009920000,1,1,1,1,3,3,0,45.00,...,IT/IS,Brian Champaigne,13.0,Indeed,Fully Meets,2.06,5,5,1/28/2019,0.0
37,"Champaigne, Brian",1009919920,1,1,1,1,3,3,0,63.50,...,IT/IS,Jennifer Zamora,5.0,Professional Society,Fully Meets,4.50,5,7,1/15/2019,0.0
38,"Zamora, Jennifer",1112030816,0,0,0,1,3,4,0,65.00,...,IT/IS,Janet King,2.0,Employee Referral,Exceeds,1.12,5,6,2/21/2019,0.0
39,"Roper, Katie",1009919950,0,0,0,1,3,3,0,55.00,...,IT/IS,Brian Champaigne,13.0,Indeed,Fully Meets,4.94,3,5,02-06-2019,0.0
40,"Becker, Renee",1102024056,0,0,0,4,3,3,0,43.00,...,IT/IS,Simon Roup,4.0,Search Engine - Google Bing Yahoo,Fully Meets,1.87,4,5,NaN,NaN
41,"Goble, Taisha",905013738,0,0,0,4,3,3,0,48.50,...,IT/IS,Simon Roup,4.0,Glassdoor,Fully Meets,1.87,4,4,NaN,NaN
42,"Hernandez, Daniff",1410071156,1,1,1,4,3,3,0,40.10,...,IT/IS,Simon Roup,4.0,Employee Referral,Fully Meets,4.33,3,7,NaN,NaN
43,"Horton, Jayne",1105025718,0,0,0,1,3,3,0,34.00,...,IT/IS,Simon Roup,4.0,Glassdoor,Fully Meets,4.48,5,6,01-03-2019,0.0
44,"Johnson, Noelle",1003018246,1,1,0,3,3,3,0,40.00,...,IT/IS,Simon Roup,4.0,Glassdoor,Fully Meets,3.75,3,5,02-11-2019,0.0
45,"Murray, Thomas",1406068403,0,2,1,1,3,4,1,35.50,...,IT/IS,Simon Roup,4.0,Diversity Job Fair,Exceeds,4.28,4,5,2/25/2019,0.0
46,"Pearson, Randall",1102023965,1,1,1,5,3,3,0,41.00,...,IT/IS,Simon Roup,4.0,Employee Referral,Fully Meets,1.62,4,5,NaN,NaN
47,"Petrowsky, Thelma",1108027853,1,1,0,1,3,4,0,42.75,...,IT/IS,Simon Roup,4.0,Employee Referral,Exceeds,3.71,5,7,01-04-2019,0.0
48,"Roby, Lori",1407068885,1,1,0,1,3,3,0,39.55,...,IT/IS,Simon Roup,4.0,Employee Referral,Fully Meets,3.69,5,6,2/14/2019,0.0
49,"Rogers, Ivan",1203032255,1,1,1,1,3,3,0,42.20,...,IT/IS,Simon Roup,4.0,Pay Per Click - Google,Fully Meets,3.04,3,6,1/22/2019,0.0
50,"Salter, Jason",1111030148,0,2,1,5,3,3,0,45.00,...,IT/IS,Simon Roup,4.0,Vendor Referral,Fully Meets,2.19,3,5,NaN,NaN
51,"Simard, Kramer",808010278,1,1,1,1,3,3,0,30.20,...,IT/IS,Simon Roup,4.0,Employee Referral,Fully Meets,3.32,3,7,1/14/2019,0.0
52,"Zhou, Julia",1110029732,0,0,0,1,3,3,0,31.40,...,IT/IS,Simon Roup,4.0,Employee Referral,Fully Meets,5.00,3,5,02-01-2019,0.0
55,"Foss, Jason",1192991000,0,0,1,1,3,4,0,65.00,...,IT/IS,Jennifer Zamora,5.0,Professional Society,Exceeds,3.76,5,5,01-07-2019,0.0
56,"Roup,Simon",1106026933,0,0,1,1,3,3,0,62.00,...,IT/IS,Jennifer Zamora,5.0,Professional Society,Fully Meets,2.96,5,7,2/18/2019,0.0
57,"Ruiz, Ricardo",1001175250,0,2,1,5,3,3,1,21.00,...,IT/IS,Jennifer Zamora,5.0,Diversity Job Fair,Fully Meets,2.51,4,6,NaN,NaN
58,"Monroe, Peter",1011022863,1,1,1,1,3,2,1,63.00,...,IT/IS,Jennifer Zamora,5.0,Diversity Job Fair,Needs Improvement,2.39,3,6,2/22/2019,0.0
59,"Dougall, Eric",1101023754,0,0,1,1,3,4,0,64.00,...,IT/IS,Jennifer Zamora,5.0,Professional Society,Exceeds,1.99,5,5,01-04-2019,0.0
60,"Clayton, Rick",1301052902,0,0,1,1,3,3,0,28.99,...,IT/IS,Eric Dougall,6.0,Glassdoor,Fully Meets,2.55,3,6,2/27/2019,0.0
61,"Galia, Lisa",1501072093,0,0,0,1,3,3,0,31.40,...,IT/IS,Eric Dougall,6.0,Vendor Referral,Fully Meets,1.21,4,5,02-01-2019,0.0
62,"Lindsay, Leonara",602000312,0,0,0,1,3,4,1,26.00,...,IT/IS,Eric Dougall,6.0,Diversity Job Fair,Exceeds,4.64,4,5,1/25/2019,0.0
63,"Soto, Julia",1203032263,1,1,0,1,3,3,0,27.49,...,IT/IS,Eric Dougall,6.0,Information Session,Fully Meets,4.30,3,5,02-08-2019,0.0
64,"Bacong, Alejandro",1212052023,0,2,1,1,3,3,0,45.00,...,IT/IS,Peter Monroe,7.0,Glassdoor,Fully Meets,1.84,5,6,2/18/2019,0.0
65,"Cisco, Anthony",1102024173,1,1,1,1,3,3,0,42.00,...,IT/IS,Peter Monroe,7.0,Information Session,Fully Meets,2.21,5,7,01-10-2019,0.0
66,"Dolan, Linda",1101023540,1,1,0,1,3,3,0,37.00,...,IT/IS,Peter Monroe,7.0,Employee Referral,Fully Meets,4.11,4,6,2/25/2019,0.0
67,"Gonzalez, Maria",1988299991,0,3,0,1,3,3,0,39.00,...,IT/IS,Peter Monroe,7.0,Employee Referral,Fully Meets,4.61,4,5,1/28/2019,0.0
68,"Merlos, Carlos",1012023013,0,0,1,1,3,1,0,43.00,...,IT/IS,Peter Monroe,7.0,Vendor Referral,PIP,1.20,3,6,02-04-2019,0.0
69,"Morway, Tanya",1001956578,1,1,0,1,3,3,0,27.00,...,IT/IS,Peter Monroe,7.0,Monster.com,Fully Meets,3.81,3,6,02-11-2019,0.0
70,"Shepard, Anita",906014183,1,1,0,1,3,3,0,47.00,...,IT/IS,Peter Monroe,7.0,Vendor Referral,Fully Meets,3.31,3,6,01-07-2019,0.0
71,"Tredinnick, Neville",1104025466,1,1,1,5,3,3,0,28.00,...,IT/IS,Peter Monroe,7.0,Monster.com,Fully Meets,5.00,3,5,NaN,NaN
72,"Turpin, Jumil",1411071506,1,1,1,1,3,3,0,49.10,...,IT/IS,Peter Monroe,7.0,Employee Referral,Fully Meets,5.00,4,7,1/14/2019,0.0
284,"Le, Binh",1009919930,0,0,0,1,3,3,0,50.25,...,IT/IS,Brian Champaigne,13.0,Indeed,Fully Meets,2.09,5,7,01-08-2019,0.0
285,"Navathe, Kurt",1009919960,0,0,1,1,3,3,0,52.25,...,IT/IS,Brian Champaigne,13.0,Indeed,Fully Meets,5.00,3,6,2/25/2019,0.0
286,"Wang, Charlie",1009919970,0,0,1,1,3,3,0,51.00,...,IT/IS,Brian Champaigne,13.0,Indeed,Fully Meets,3.42,4,7,01-04-2019,0.0
301,"Ait Sidi, Karthikeyan",1307060199,1,1,1,5,3,3,0,62.00,...,IT/IS,Simon Roup,4.0,Company Intranet - Partner,Fully Meets,4.96,3,6,NaN,NaN
302,"Carr, Claudia N",1010022337,0,0,0,2,3,3,0,61.30,...,IT/IS,Simon Roup,4.0,Vendor Referral,Fully Meets,5.00,5,6,2/18/2019,0.0
303,"Favis, Donald",1412071562,0,0,1,4,3,3,0,58.20,...,IT/IS,Simon Roup,4.0,Vendor Referral,Fully Meets,2.94,5,7,NaN,NaN
304,"Roehrich, Bianca",1111030266,0,0,0,5,3,3,0,58.50,...,IT/IS,Simon Roup,4.0,Vendor Referral,Fully Meets,3.88,3,7,NaN,NaN
305,"Daniele, Ann",1411071312,1,1,0,3,3,3,0,54.10,...,IT/IS,Peter Monroe,7.0,Vendor Referral,Fully Meets,1.55,5,8,02-12-2019,0.0
306,"Lajiri, Jyoti",1108028108,1,1,1,3,3,3,0,56.20,...,IT/IS,Peter Monroe,7.0,Employee Referral,Fully Meets,4.46,5,6,01-07-2019,0.0
307,"Semizoglou, Jeremiah",904013591,1,1,1,2,3,3,0,53.80,...,IT/IS,Peter Monroe,7.0,On-campus Recruiting,Fully Meets,3.27,4,5,1/14/2019,0.0
308,"South, Joe",1308060959,0,0,1,1,3,3,0,53.00,...,IT/IS,Peter Monroe,7.0,Employee Referral,Fully Meets,5.00,3,4,01-02-2019,0.0
309,"Warfield, Sarah",1301052347,0,4,0,1,3,3,0,55.20,...,IT/IS,Peter Monroe,7.0,Employee Referral,Fully Meets,1.06,4,8,02-05-2019,0.0

In [9]:
df[df["Department"] != 'Admin Offices']
# We get all those rows with "Department" other than "Admin Offices".

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,PayRate,...,Department,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30
6,"Bunbury, Jessica",1504073368,1,1,0,5,6,3,0,55.0,...,Sales,John Smith,17.0,Social Networks - Facebook Twitter etc,Fully Meets,3.14,5,0,NaN,NaN
7,"Carter, Michelle",1403065721,0,0,0,1,6,3,0,55.0,...,Sales,John Smith,17.0,Billboard,Fully Meets,5.00,5,0,1/21/2019,0.0
8,"Dietrich, Jenna",1408069481,0,0,0,1,6,1,0,55.0,...,Sales,John Smith,17.0,Website Banner Ads,PIP,2.30,1,0,1/29/2019,0.0
9,"Digitale, Alfred",1306059197,1,1,1,1,6,3,0,56.0,...,Sales,John Smith,17.0,Pay Per Click - Google,Fully Meets,3.60,5,0,1/30/2019,0.0
10,"Friedman, Gerry",1204032843,0,0,1,1,6,3,1,55.5,...,Sales,John Smith,17.0,Diversity Job Fair,Fully Meets,3.65,5,0,1/17/2019,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
305,"Daniele, Ann",1411071312,1,1,0,3,3,3,0,54.1,...,IT/IS,Peter Monroe,7.0,Vendor Referral,Fully Meets,1.55,5,8,02-12-2019,0.0
306,"Lajiri, Jyoti",1108028108,1,1,1,3,3,3,0,56.2,...,IT/IS,Peter Monroe,7.0,Employee Referral,Fully Meets,4.46,5,6,01-07-2019,0.0
307,"Semizoglou, Jeremiah",904013591,1,1,1,2,3,3,0,53.8,...,IT/IS,Peter Monroe,7.0,On-campus Recruiting,Fully Meets,3.27,4,5,1/14/2019,0.0
308,"South, Joe",1308060959,0,0,1,1,3,3,0,53.0,...,IT/IS,Peter Monroe,7.0,Employee Referral,Fully Meets,5.00,3,4,01-02-2019,0.0
309,"Warfield, Sarah",1301052347,0,4,0,1,3,3,0,55.2,...,IT/IS,Peter Monroe,7.0,Employee Referral,Fully Meets,1.06,4,8,02-05-2019,0.0

In [10]:
df[df["DOB"] <= "09/26/84"]

,Employee_Name,EmpID,MarriedID,MaritalStatusID,GenderID,EmpStatusID,DeptID,PerfScoreID,FromDiversityJobFairID,PayRate,...,Department,ManagerName,ManagerID,RecruitmentSource,PerformanceScore,EngagementSurvey,EmpSatisfaction,SpecialProjectsCount,LastPerformanceReview_Date,DaysLateLast30
1,"LaRotonda, William",1106026572,0,2,1,1,1,3,0,23.00,...,Admin Offices,Brandon R. LeBlanc,1.0,Website Banner Ads,Fully Meets,5.00,4,4,1/17/2019,0.0
2,"Steans, Tyrone",1302053333,0,0,1,1,1,3,0,29.00,...,Admin Offices,Brandon R. LeBlanc,1.0,Internet Search,Fully Meets,3.90,5,5,1/18/2019,0.0
3,"Howard, Estelle",1211050782,1,1,0,1,1,3,0,21.50,...,Admin Offices,Brandon R. LeBlanc,1.0,Pay Per Click - Google,Fully Meets,3.24,3,4,NaN,NaN
4,"Singh, Nan",1307059817,0,0,0,1,1,3,0,16.56,...,Admin Offices,Brandon R. LeBlanc,1.0,Website Banner Ads,Fully Meets,5.00,3,5,1/15/2019,0.0
5,"Smith, Leigh Ann",711007713,1,1,0,5,1,3,1,20.50,...,Admin Offices,Brandon R. LeBlanc,1.0,Diversity Job Fair,Fully Meets,3.80,4,4,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
305,"Daniele, Ann",1411071312,1,1,0,3,3,3,0,54.10,...,IT/IS,Peter Monroe,7.0,Vendor Referral,Fully Meets,1.55,5,8,02-12-2019,0.0
306,"Lajiri, Jyoti",1108028108,1,1,1,3,3,3,0,56.20,...,IT/IS,Peter Monroe,7.0,Employee Referral,Fully Meets,4.46,5,6,01-07-2019,0.0
307,"Semizoglou, Jeremiah",904013591,1,1,1,2,3,3,0,53.80,...,IT/IS,Peter Monroe,7.0,On-campus Recruiting,Fully Meets,3.27,4,5,1/14/2019,0.0
308,"South, Joe",1308060959,0,0,1,1,3,3,0,53.00,...,IT/IS,Peter Monroe,7.0,Employee Referral,Fully Meets,5.00,3,4,01-02-2019,0.0
309,"Warfield, Sarah",1301052347,0,4,0,1,3,3,0,55.20,...,IT/IS,Peter Monroe,7.0,Employee Referral,Fully Meets,1.06,4,8,02-05-2019,0.0

Similarly, we can also use <,>=,> as well.